// Date: 1/2/2014 11:15:40 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class Modelparasite extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Leg;
    ModelRenderer leg2;
    ModelRenderer Body;
    ModelRenderer Leg;
    ModelRenderer Leg;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Body;
    ModelRenderer Leg;
    ModelRenderer Leg;
  
  public Modelparasite()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(-2F, -1F, -2F, 3, 3, 3);
      Body.setRotationPoint(-1F, 22F, -2F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Leg = new ModelRenderer(this, 0, 0);
      Leg.addBox(0F, 0F, 0F, 4, 1, 1);
      Leg.setRotationPoint(0F, 23F, -3F);
      Leg.setTextureSize(64, 32);
      Leg.mirror = true;
      setRotation(Leg, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 0, 0);
      leg2.addBox(0F, 0F, 0F, 4, 1, 1);
      leg2.setRotationPoint(-3F, 23F, -2F);
      leg2.setTextureSize(64, 32);
      leg2.mirror = true;
      setRotation(leg2, 0F, 3.141593F, 0F);
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(-1F, -1F, -1F, 3, 3, 3);
      Body.setRotationPoint(-2F, 22F, 0F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Leg = new ModelRenderer(this, 0, 0);
      Leg.addBox(0F, 0F, 0F, 4, 1, 1);
      Leg.setRotationPoint(0F, 23F, 0F);
      Leg.setTextureSize(64, 32);
      Leg.mirror = true;
      setRotation(Leg, 0F, 0F, 0F);
      Leg = new ModelRenderer(this, 0, 0);
      Leg.addBox(0F, 0F, 0F, 4, 1, 1);
      Leg.setRotationPoint(-3F, 24F, 0F);
      Leg.setTextureSize(64, 32);
      Leg.mirror = true;
      setRotation(Leg, 0F, 0F, -3.141593F);
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 1F, -1F, 1, 1, 1);
      Shape1.setRotationPoint(-1F, 21F, -4F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, -1F, 1, 1, 1);
      Shape1.setRotationPoint(-3F, 22F, -4F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(-1F, -1F, -1F, 3, 3, 3);
      Body.setRotationPoint(-2F, 22F, 3F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Leg = new ModelRenderer(this, 0, 0);
      Leg.addBox(0F, 0F, 0F, 4, 1, 1);
      Leg.setRotationPoint(0F, 23F, 3F);
      Leg.setTextureSize(64, 32);
      Leg.mirror = true;
      setRotation(Leg, 0F, 0F, 0F);
      Leg = new ModelRenderer(this, 0, 0);
      Leg.addBox(0F, 0F, 0F, 4, 1, 1);
      Leg.setRotationPoint(-3F, 23F, 4F);
      Leg.setTextureSize(64, 32);
      Leg.mirror = true;
      setRotation(Leg, 0F, 3.141593F, 0.0371786F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Body.render(f5);
    Leg.render(f5);
    leg2.render(f5);
    Body.render(f5);
    Leg.render(f5);
    Leg.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Body.render(f5);
    Leg.render(f5);
    Leg.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
