// Date: 1/6/2014 9:53:57 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelVoidDemon extends ModelBase
{
  //fields
    ModelRenderer Head;
    ModelRenderer Body;
    ModelRenderer Neck;
    ModelRenderer rightBicept;
    ModelRenderer Left_bicept;
    ModelRenderer right_forearm;
    ModelRenderer leftforearm;
    ModelRenderer waist;
    ModelRenderer rightlegtop;
    ModelRenderer rightlegtop;
    ModelRenderer rightlegmiddle;
    ModelRenderer rightlegmiddle;
    ModelRenderer left_wing_base;
    ModelRenderer right_wing_base;
    ModelRenderer rightlegbottom;
    ModelRenderer rightlegmiddle;
    ModelRenderer lefthoof;
    ModelRenderer righthoof;
    ModelRenderer horn_left;
    ModelRenderer horn_right;
    ModelRenderer horn_right;
    ModelRenderer horn_right;
  
  public ModelVoidDemon()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Head = new ModelRenderer(this, 0, 0);
      Head.addBox(-3F, -5F, -2F, 5, 5, 5);
      Head.setRotationPoint(2F, -5F, -1F);
      Head.setTextureSize(64, 32);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Body = new ModelRenderer(this, 0, 10);
      Body.addBox(-4F, 0F, -3F, 7, 9, 5);
      Body.setRotationPoint(2F, -3F, 0F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Neck = new ModelRenderer(this, 24, 43);
      Neck.addBox(-1F, 0F, -2F, 3, 2, 3);
      Neck.setRotationPoint(1F, -5F, 0F);
      Neck.setTextureSize(64, 32);
      Neck.mirror = true;
      setRotation(Neck, 0F, 0F, 0F);
      rightBicept = new ModelRenderer(this, 18, 58);
      rightBicept.addBox(-8F, -1F, -1F, 8, 3, 3);
      rightBicept.setRotationPoint(-1F, -2F, -1F);
      rightBicept.setTextureSize(64, 32);
      rightBicept.mirror = true;
      setRotation(rightBicept, 0F, 0F, 0F);
      Left_bicept = new ModelRenderer(this, 18, 52);
      Left_bicept.addBox(0F, -2F, -2F, 8, 3, 3);
      Left_bicept.setRotationPoint(4F, -1F, 0F);
      Left_bicept.setTextureSize(64, 32);
      Left_bicept.mirror = true;
      setRotation(Left_bicept, 0F, 0F, 0F);
      right_forearm = new ModelRenderer(this, 0, 52);
      right_forearm.addBox(-6F, -1F, -1F, 6, 3, 3);
      right_forearm.setRotationPoint(-8F, -2F, -1F);
      right_forearm.setTextureSize(64, 32);
      right_forearm.mirror = true;
      setRotation(right_forearm, 0F, 0F, 0F);
      leftforearm = new ModelRenderer(this, 0, 58);
      leftforearm.addBox(0F, -1F, -1F, 6, 3, 3);
      leftforearm.setRotationPoint(11F, -2F, -1F);
      leftforearm.setTextureSize(64, 32);
      leftforearm.mirror = true;
      setRotation(leftforearm, 0F, 0F, 0F);
      waist = new ModelRenderer(this, 0, 24);
      waist.addBox(-4F, 0F, -2F, 7, 4, 5);
      waist.setRotationPoint(2F, 5F, -1F);
      waist.setTextureSize(64, 32);
      waist.mirror = true;
      setRotation(waist, 0F, 0F, 0F);
      rightlegtop = new ModelRenderer(this, 0, 33);
      rightlegtop.addBox(-3F, 0F, -1F, 4, 6, 4);
      rightlegtop.setRotationPoint(0F, 7F, -1F);
      rightlegtop.setTextureSize(64, 32);
      rightlegtop.mirror = true;
      setRotation(rightlegtop, 0F, 0F, 0F);
      rightlegtop = new ModelRenderer(this, 16, 33);
      rightlegtop.addBox(0F, 0F, 0F, 4, 6, 4);
      rightlegtop.setRotationPoint(2F, 7F, -2F);
      rightlegtop.setTextureSize(64, 32);
      rightlegtop.mirror = true;
      setRotation(rightlegtop, 0F, 0F, 0F);
      rightlegmiddle = new ModelRenderer(this, 24, 15);
      rightlegmiddle.addBox(-2F, 0F, -2F, 3, 6, 3);
      rightlegmiddle.setRotationPoint(-1F, 12F, 1F);
      rightlegmiddle.setTextureSize(64, 32);
      rightlegmiddle.mirror = true;
      setRotation(rightlegmiddle, -0.5235988F, 0F, 0F);
      rightlegmiddle = new ModelRenderer(this, 24, 24);
      rightlegmiddle.addBox(-1F, 0F, -1F, 3, 6, 3);
      rightlegmiddle.setRotationPoint(4F, 12F, 0F);
      rightlegmiddle.setTextureSize(64, 32);
      rightlegmiddle.mirror = true;
      setRotation(rightlegmiddle, -0.5235988F, 0F, 0F);
      left_wing_base = new ModelRenderer(this, 20, 0);
      left_wing_base.addBox(0F, 0F, 0F, 1, 1, 7);
      left_wing_base.setRotationPoint(3F, -2F, 1F);
      left_wing_base.setTextureSize(64, 32);
      left_wing_base.mirror = true;
      setRotation(left_wing_base, 1.047198F, 0F, 0.5235988F);
      right_wing_base = new ModelRenderer(this, 36, 0);
      right_wing_base.addBox(0F, 0F, 0F, 1, 1, 7);
      right_wing_base.setRotationPoint(-1F, -2F, 1F);
      right_wing_base.setTextureSize(64, 32);
      right_wing_base.mirror = true;
      setRotation(right_wing_base, 1.047198F, 0F, -0.5235988F);
      rightlegbottom = new ModelRenderer(this, 12, 43);
      rightlegbottom.addBox(-1F, 0F, -2F, 3, 6, 3);
      rightlegbottom.setRotationPoint(4F, 16F, -2F);
      rightlegbottom.setTextureSize(64, 32);
      rightlegbottom.mirror = true;
      setRotation(rightlegbottom, 0.3490659F, 0F, 0F);
      rightlegmiddle = new ModelRenderer(this, 0, 43);
      rightlegmiddle.addBox(-2F, 0F, -1F, 3, 6, 3);
      rightlegmiddle.setRotationPoint(-1F, 16F, -3F);
      rightlegmiddle.setTextureSize(64, 32);
      rightlegmiddle.mirror = true;
      setRotation(rightlegmiddle, 0.3490659F, 0F, 0F);
      lefthoof = new ModelRenderer(this, 24, 8);
      lefthoof.addBox(-1F, 0F, -1F, 3, 3, 3);
      lefthoof.setRotationPoint(4F, 21F, -1F);
      lefthoof.setTextureSize(64, 32);
      lefthoof.mirror = true;
      setRotation(lefthoof, 0F, 0F, 0F);
      righthoof = new ModelRenderer(this, 24, 8);
      righthoof.addBox(-1F, 0F, -1F, 3, 3, 3);
      righthoof.setRotationPoint(-2F, 21F, -1F);
      righthoof.setTextureSize(64, 32);
      righthoof.mirror = true;
      setRotation(righthoof, 0F, 0F, 0F);
      horn_left = new ModelRenderer(this, 40, 11);
      horn_left.addBox(-1F, -4F, 0F, 1, 4, 1);
      horn_left.setRotationPoint(4F, -9F, -2F);
      horn_left.setTextureSize(64, 32);
      horn_left.mirror = true;
      setRotation(horn_left, -0.5235988F, 0F, 0F);
      horn_right = new ModelRenderer(this, 36, 11);
      horn_right.addBox(-1F, -4F, 0F, 1, 4, 1);
      horn_right.setRotationPoint(0F, -9F, -2F);
      horn_right.setTextureSize(64, 32);
      horn_right.mirror = true;
      setRotation(horn_right, -0.5235988F, 0F, 0F);
      horn_right = new ModelRenderer(this, 36, 8);
      horn_right.addBox(-1F, -2F, 0F, 1, 2, 1);
      horn_right.setRotationPoint(0F, -12F, 0F);
      horn_right.setTextureSize(64, 32);
      horn_right.mirror = true;
      setRotation(horn_right, -0.5235988F, 0F, 0.5235988F);
      horn_right = new ModelRenderer(this, 40, 8);
      horn_right.addBox(0F, -2F, 0F, 1, 2, 1);
      horn_right.setRotationPoint(3F, -12F, 0F);
      horn_right.setTextureSize(64, 32);
      horn_right.mirror = true;
      setRotation(horn_right, -0.5235988F, 0F, -0.5235988F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Head.render(f5);
    Body.render(f5);
    Neck.render(f5);
    rightBicept.render(f5);
    Left_bicept.render(f5);
    right_forearm.render(f5);
    leftforearm.render(f5);
    waist.render(f5);
    rightlegtop.render(f5);
    rightlegtop.render(f5);
    rightlegmiddle.render(f5);
    rightlegmiddle.render(f5);
    left_wing_base.render(f5);
    right_wing_base.render(f5);
    rightlegbottom.render(f5);
    rightlegmiddle.render(f5);
    lefthoof.render(f5);
    righthoof.render(f5);
    horn_left.render(f5);
    horn_right.render(f5);
    horn_right.render(f5);
    horn_right.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
